import Head from 'next/head'
import Center from '../components/Center';
import Sidebar from "../components/Sidebar";
import Player from "../components/Player";
import { getSession } from "next-auth/react";

export default function Home() {
  <Head>
    <title>Spotify</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>;

  return (
    // To make the Scrolling effect smoother & fixed!
    <div className="bg-black h-screen overflow-hidden">
        <main className="flex">
          <Sidebar />
          <Center />
        </main>

        <div className="sticky bottom-0">
          <Player />
        </div>
    </div>
  );
}

// We need to pre-render the session, so that we can get the playlistDetails after refreshing!
export async function getServerSideProps(context) {
  const session = await getSession(context);
  
  return {
    props: {
      session,
    }
  }
}
